[package]
name = "ja-report"
version = "1.1.3"
entrypoint = "report.typ"
authors = ["Yuya KAMATAKI"]
license = "Unlicense"
description = "typst templates for Japanese"
repository = "https://github.com/YKamataki/typst_templates"
homepage = ""
keywords = [
    "Japanese",
    "report",
]
compiler = "0.7.0"
exclude = ["report.pdf"]

[utpm]
version = "2"
